### PR TITLE
Update: Only have lodash template dependency and remove big lodash

### PR DESCRIPTION
**Pull request by gyandeeps**

### CODE REVIEW

**Comment by maenu** [comment]
I was wondering if there wasn't a way to get rid of the lodash dependency completely. Is there a way to pass the template source back to the jasmine task to render it?

**Comment by gyandeeps** [comment]
@maenu I will look into it.

**Comment by gyandeeps** [comment]
Based on the research, if we try to remove lodash template then we would have to do a lot of stuff. since lodash already does the work smartly for us, i think we should stick with it.

**Comment by maenu** [comment]
You are right, I couldn't find a way either. grunt-contrib-jasmine [uses lodash](https://github.com/gruntjs/grunt-contrib-jasmine/blob/master/tasks/lib/jasmine.js#L116) too. grunt-template-jasmine-requirejs [uses grunt.util._](https://github.com/cloudchen/grunt-template-jasmine-requirejs/blob/master/src/template-jasmine-requirejs.js#L176) and does not have a dependency to lodash. But grunt.util._ [is deprecated](http://gruntjs.com/api/grunt.util#grunt.util._).
I'd say we should render the mixed in template as grunt-contrib-jasmine does - with lodash. As we do not have the render method from jasmine in the task object (that would be nice though), we should have the same dependency.
So I'm okay with this PR.

**Pull request merged**
