### PR TITLE
Upgraded NPM dependencies, src and tests to use Grunt 1.0

### PR DESCRIPTION
**Pull request by radum**
I updated this so it an work with latest version of Jasmine and Grunt 1.0. Let me know what are your thoughts about this.

### CODE REVIEW

**Comment by maenu** [comment]
Nice work, thanks a lot. I will have a look at it.
I didn't even know Grunt was stable on v1.0 already.

**Comment by radum** [comment]
@maenu 

> We will also be changing the behavior of peerDependencies in npm@3. We won’t be automatically downloading the peer dependency anymore. Instead, we’ll warn you if the peer dependency isn’t already installed. This requires you to resolve peerDependency conflicts yourself, manually, but in the long run this should make it less likely that you’ll end up in a tricky spot with your packages’ dependencies.

They are not automatically installed [now](https://docs.npmjs.com/files/package.json#peerdependencies).

**Comment by radum** [comment]
Ping @maenu

**Comment by maenu** [comment]
Hm, I liked the old behavior of peerDependencies. But I still want to keep the peerDependencies, they still give a useful hint on what version to install.
If you fix those two things, I'll merge:
1. `grunt-template-jasmine-requirejs` is mentioned in `README.md`, I guess you meant something else.
2. Re-add peerDependencies

Then we should uniformly use `^a.b.c` instead `>=.a.b.c`, we had issues with that before in #41, no idea where we lost that. I can do that after merging, or you can also do that, if you want.

**Comment by radum** [comment]
@maenu The old behavior of peerDependencies IMHO was there to tell the user that this npm module will work if you have these peerDependencies installed, so let me do that for you.

But users have different requirements, some need a specific version of Grunt or any other module listed as a peer dependency. So assuming a required module can help the main `app` (that requires the module) with its dependencies is a bit wrong.

With the introduction of NPM3, peerDependencies behaves differently. It no longer actually installs the peerDependency packages. Instead, it just checks at the end of install to see that they are resolvable, and prints a warning if they are not.

I get what you are saying and I will update the PR with it, but `grunt` and `grunt-contrib-jasmine` are dev deps in my mind, as you only use them for dev. Warning the user about them I think it is pointless.

**Comment by maenu** [comment]
I disagree, `grunt` and `grunt-contrib-jasmine` are not just devDependencies, you need them to use this module. They are dev- AND peerDependencies. A module should formalize a description of the environment it will work in. I don't think it does any harm and it is not pointless.

The situation I want to avoid is the following: You installed a module and it doesn't work, raising an exception in internal code that didn't give any clue about how to fix it. So you search using the error message as a query and find a bunch of different proposed solutions, you try some of them - in the end you find out a dependency was too old. Sounds familiar? This frustration can be avoided if dependencies are actively managed - exactly what npm is supposed to do. If we declare to npm that this module requires at least jasmine 1.0.2, a user trying to use jasmine 1.0.1 will be warned with proper message and won't have to debug.

**Comment by radum** [comment]
@maenu I totally hear you, but here we can agree to disagree :) I think that if you install a module that you don't know what it needs to work and you are just waiting for the system to help you is wrong. This is also how the npm works now, on this principle.

This is not the point, I have nothing against adding the peer deps back, but in order to move this fwd the only question now is if you want me to add them to peer and dev deps also?

So that when one does npm install they will actually get installed so he can develop the module. Removing the manual running npm install for both of them.

Those 2 in the context of this particular module they are only used for dev. So do you want me to add them in both places? If not, I more than happy to keep them in peers only (probably a comment in the readme file will be required to tell contributors they need to npm install the others) and merge this PR.

**Comment by maenu** [comment]
You make my gears grind, I consider that a good thing :)

Ok, here is another view on the problem:

We have two use cases for this module: one is developing it, the other is using it. In both cases, an `npm install` should setup as much as possible. The modules we a required in both use cases are [`path`, `grunt`, `istanbul` and `lodash.template`](https://github.com/maenu/grunt-template-jasmine-istanbul/blob/master/src/main/js/template.js#L7-L10). `path` is a standard node library, it comes with node itself. `istanbul` and `lodash.template` can be isolated, we don't need to share them. `grunt` on the other hand, should be provided, as this module will be executed in the that context. And then we are implicitly relying on [`grunt-contrib-jasmine`](https://github.com/maenu/grunt-template-jasmine-istanbul/blob/master/src/main/js/template.js#L14), which also should be provided.

In the case of developing this module, we are have everything set up, if we have `grunt` and `grunt-contrib-jasmine` as devDependencies. If we just use the module as a dependency, setting both in peerDependencies will make sure, that the user is given the information to install both with appropriate version. The peerDependencies will be met by the devDependencies, so `npm install` installs everything we need.

So yes, please add `grunt` and `grunt-contrib-jasmine` as peerDependencies and devDependencies with same version qualifier.

**Comment by radum** [comment]
All done now @maenu 😀

**Comment by maenu** [comment]
Merged, tested and published. Thanks again.

**Pull request merged**
